### ISSUE TITLE
Escaped quote at end of string results in broken token

### ISSUE THREAD

**Issue by janvlug** [atextor/owl-cli#10]
Take this file with escaped double quotes (`\""`) at the end of a string:
[quote_issue_org.txt](https://github.com/atextor/owl-cli/files/12004679/quote_issue_org.txt)
run:
```
owl-x86_64-linux-1.2.3 write quote_issue_org.txt  quote_issue_orgi_2.txt
```
All goes well, compare the files `quote_issue_org.txt` and `quote_issue_org_2.txt` and note the differences.

Next run:
```
owl-x86_64-linux-1.2.3 write quote_issue_org_2.txt quote_issue_org_3.txt
```
The result is:
```
2023-07-10 19:20:11,930 ERROR o.a.j.riot: [line: 10, col: 1 ] Broken token (newline): @nl .
Error: [line: 10, col: 1 ] Broken token (newline): @nl .
```
Note that changing the `""""` in `quote_issue_org_2.txt` into `" """` makes owl-cli work again

**Comment by atextor** [comment]
Hi @janvlug,
thanks for reporting! owl-cli uses [turtle-formatter](https://github.com/atextor/turtle-formatter) for writing RDF/OWL and whenever a string contains either newlines or quotes, it will use triple quotes. quote_issue_org_2.txt will look like this:

```turtle
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix janont: <https://identifier.overheid.nl/test/jan/ont/> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .

<https://identifier.jan.nl/test/jan/ont-0.3.0-SNAPSHOT> a owl:Ontology .

janont:Product a owl:Class ;
  skos:definition """Iets dat is "geproduceerd.""""@nl .
```

This is valid RDF/Turtle, so the written file is correct. However, loading such a file (which is done by owl-cli using Apache Jena) fails, because the quote directly followed by the triple quote is not parsed correctly it seems. I have opened a [corresponding issue](https://github.com/apache/jena/issues/1956) with Jena, let's see if it can get fixed there. Otherwise, we'd have to build a workaround, e.g., by automatically inserting a space before the closing triple quote. I'd rather not do this though, because then formatting a file would alter its contents, which should obviously be a no-go.
